<form action="" method="POST">
    <div class="container">
        <h1>Регистрация</h1>

        <p>Введите данные для создания аккаунта</p>

        <hr>
        <label for="last name"><b>Фамилия</b>
            <span style="color: red">
                <?= $errors['lastName'] ?? ''; ?>
            </span>
        </label>
        <label>
            <input type="text" placeholder="Введите фамилию" name="last name" required>
        </label>


        <label for="first name"><b>Имя</b>
            <span style="color: red">
                <?= $errors['firstName'] ?? ''; ?>
            </span>
        </label>
        <label>
            <input type="text" placeholder="Введите имя" name="first name" required>
        </label>

        <label for="middle name"><b>Отчество</b>
            <span style="color: red">
                <?= $errors['middleName'] ?? ''; ?>
            </span>
        </label>
        <label>
            <input type="text" placeholder="Введите отчество" name="middle name">
        </label>

        <label for="email"><b>Электронная почта</b>
            <span style="color: red">
                <?= $errors['email'] ?? ''; ?>
            </span>
        </label>
        <label>
            <input type="text" placeholder="Введите адрес электронной почты" name="email" required>
        </label>

        <label for="phone number"><b>Телефон</b>
            <span style="color: red">
                <?= $errors['phoneNumber'] ?? ''; ?>
            </span>
        </label>
        <label>
            <input type="text" placeholder="Введите номер телефона" name="phone number" required>
        </label>


        <label for="password"><b>Пароль</b>
            <span style="color: red">
                <?= $errors['password'] ?? ''; ?>
            </span>
        </label>
        <input type="password" placeholder="Введите пароль" name="password" required>


        <button type="submit" class="registerbtn">Зарегистрироваться</button>
    </div>
</form>

<style>
    * {box-sizing: border-box}

    /* Add padding to containers */
    .container {
        padding: 16px;
    }

    /* Full-width input fields */
    input[type=text], input[type=password] {
        width: 100%;
        padding: 15px;
        margin: 5px 0 22px 0;
        display: inline-block;
        border: none;
        background: #f1f1f1;
    }

    input[type=text]:focus, input[type=password]:focus {
        background-color: #ddd;
        outline: none;
    }

    /* Overwrite default styles of hr */
    hr {
        border: 1px solid #f1f1f1;
        margin-bottom: 25px;
    }

    /* Set a style for the submit/register button */
    .registerbtn {
        background-color: #4CAF50;
        color: white;
        padding: 16px 20px;
        margin: 8px 0;
        border: none;
        cursor: pointer;
        width: 100%;
        opacity: 0.9;
    }

    .registerbtn:hover {
        opacity:1;
    }

    /* Add a blue text color to links */
    a {
        color: dodgerblue;
    }

    /* Set a grey background color and center the text of the "sign in" section */
    .signin {
        background-color: #f1f1f1;
        text-align: center;
    }
</style>