<div class="container">
    <h2>Something's wrong here...</h2>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Questionmark_copyright.svg/2000px-Questionmark_copyright.svg.png" ALIGN="right"/>

<style>
    @import url("https://fonts.googleapis.com/css?family=Advent Pro");
    body{
        background: #2d5986;
        color: #eee;
        justify-content: space-around;
    }
    .container{
        margin-top: 5px;
    }
    img{
        height: 320px;
        float: right;
        margin-right: 10%;
    }
    h2{
        font-size: 3em;
        font-family: 'Advent Pro';
    }
    h6{
        font-size: 1.2em;
        font-family: 'Advent Pro';
    }
    .btn-1{
        background: transparent;
        color: white;
        border 1px;
        border-color: white;
        height: 50px;
        width: 200px;
        margin-right: 5px;
    }
    a{
        text-decoration: none;
        color: white;
    }
    .btn-2 {
        background: white;
        color: #2d5986;
        border 1px;
        border-color: white;
        height: 50px;
        width: 200px;
    }
    .a-2{
        color: #2d5686;
    }
    @media(max-width: 700px){
        img{
            height: 250px;
        }
        .btn-1, .btn-2{
            display: flex;
            flex-direction: column;
            width: 200px;
            margin-left: 5%;
            font-size: 1em;
            padding: 20px;
        }
    }
    @media(max-width: 500px){
        img{
            height: 200px;
        }
        .btn-1, .btn-2{
            height: 30px;
            width: 130px;
        }
    }
    @media(max-width: 360px){
        img{
            height: 170px;
        }
    }
</style>