<div class="LoginPageContainer">
    <div class="LoginPageInnerContainer">

        <div class="ImageContianer">
            <img src="https://i.imgur.com/MYZd7of.png" class="GroupImage">
        </div>

        <div class="LoginFormContainer">
            <div class="LoginFormInnerContainer">
                <header class="header">Sign In</header>

                <form action="" method="POST">
                    <div class="inputContainer">
                        <label class="label" for="email"><img src="https://i.imgur.com/Hn13wvm.png" class="labelIcon"><span>
                                Email Address
                                </span>
                            <span style="color: red">
                                *
                                </span>
                                <span style="color: red">
                                    <?= ($errors['email'] ?? ''); ?>
                                </span>
                        </label>
                        <label>
                            <input type="text" class="input" name="email" placeholder="Enter your Email Address">
                        </label>
                    </div>
                    <div class="inputContainer">
                        <label class="label" for="password"><img src="https://i.imgur.com/g5SvdfG.png"
                                                                     class="labelIcon"><span>Password
                                </span>
                                <span style="color: red">
                                    *
                                </span>
                                <span style="color: red">
                                    <?= ($errors['password'] ?? ''); ?>
                                </span>
                        </label>
                        <label>
                            <input type="password" class="input" name="password" placeholder="Enter your Password">
                        </label>
                    </div>
                    <div>
                        <span style="color: red">
                            <?= $errors['verify'] ?? ''; ?>
                        </span>
                    </div>
                    <button type="submit" class="LoginButton">Login</button>
                </form>

            </div>
        </div>

    </div>
</div>

<style>
    * {
        margin: 0px;
        font-family: Rubik;
    }

    .LoginPageContainer {
        height: 100vh;
        overflow: auto;
    }

    .LoginPageInnerContainer {
        display: flex;
        min-height: 100%;
    }

    .LoginPageInnerContainer .ImageContianer {
        width: 25%;
        background-color: #e1dfec;
        min-height: 100%;
        padding: 5%;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .LoginPageInnerContainer .ImageContianer .GroupImage {
        width: 100%;
        display: block;
    }

    .LoginPageInnerContainer .LoginFormContainer {
        flex-grow: 2;
        min-height: 100%;
        padding: 5%;
        background: white url(https://i.imgur.com/BKyjjFa.png) no-repeat fixed center center;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }

    .LoginPageInnerContainer .LoginFormContainer {
        height: 60px;
        margin-bottom: 30px;
    }

    .LoginPageInnerContainer .LoginFormContainer .header {
        font-size: 32px;
        font-weight: 500;
    }

    .LoginPageInnerContainer .LoginFormContainer {
        color: #9aa4ad;
        margin-top: 5px;
        margin-bottom: 40px;
    }

    .LoginPageInnerContainer .LoginFormContainer .inputContainer {
        color: #3f3f45;
        margin: 20px 0px;
    }

    .LoginPageInnerContainer .LoginFormContainer .inputContainer .label {
        display: flex;
        width: 100%;
        justify-content: flex-start;
        align-items: center;
        margin-right: 7px;
        margin-bottom: 10px;
    }

    .LoginPageInnerContainer .LoginFormContainer .inputContainer .label .labelIcon {
        width: 20px;
        margin-right: 10px;
        display: block;
    }

    .LoginPageInnerContainer .LoginFormContainer .inputContainer .input {
        display: block;
        width: calc(100% - 20px);
        font-size: 15px;
        padding: 10px;
        border: 1px solid #d6d7db;
        border-radius: 5px;
        margin-top: 5px;
        outline: 0px !important;
    }

    .LoginPageInnerContainer .LoginFormContainer {
        display: flex;
        justify-content: space-between;
    }

    .LoginFormContainer {
        display: flex;
        align-items: center;
    }

    .LoginFormInnerContainer {
        max-width: 500px;
    }

    .LoginPageInnerContainer .LoginFormContainer  {
        width: 15px;
        height: 15px;
        margin: 0px;
        display: block;
        border: 1px solid #d6d7db;
    }

    .LoginPageInnerContainer .LoginFormContainer  {
        display: flex;
        justify-content: flex-start;
        align-items: center;
    }

    .LoginPageInnerContainer .LoginFormContainer .checkboxContainer label {
        display: block;
        padding: 0px 5px;
        color: #9aa4ad;
    }

    .LoginPageInnerContainer .LoginFormContainer {
        color: #e7483b;
        text-decoration: none;
    }

    .LoginFormContainer .LoginFormInnerContainer .LoginButton {
        margin-top: 30px;
        display: block;
        width: 100%;
        padding: 10px;
        border-radius: 20px;
        font-weight: bold;
        color: white;
        background-color: #2e1f7a;
        border: 0px;
        outline: 0px;
        cursor: pointer;
    }

    .LoginFormContainer .LoginFormInnerContainer .LoginButton:active {
        background-color: #4520ff;
    }


    @media only screen and (max-width: 1200px) {
        .LoginPageInnerContainer .ImageContianer {
            width: 50%;
        }
    }

    @media only screen and (max-width: 800px) {
        .LoginPageInnerContainer .ImageContianer {
            display: none;
        }

        .LoginFormContainer {
            justify-content: center;
        }
    }
    .LoginPageContainer::-webkit-scrollbar {
        width: 5px;
    }

    .LoginPageContainer::-webkit-scrollbar-track {
        background: #f1f1f1;
    }

    .LoginPageContainer::-webkit-scrollbar-thumb {
        background: #2e1f7a;
    }

    .LoginPageContainer::-webkit-scrollbar-thumb:hover {
        background: #4520ff;
    }
</style>