<div class="body" align="center" action="" method="POST">
    <div class="categories body_inner" >
        <?php
            /** @var \App\Entity\Category $category */
            foreach ($categories as $category):
        ?>
            <div class="category">
                <div class="category_image">
                    <img class="category_image_inner" src="<?= $category->getImage(); ?>"
                </div>

                <div class="category_name">
                    <h3><?= $category->getName(); ?></h3>
                </div>

                <a class="category_go-to_button" href="/catalog/<?= $category->getId(); ?>">
                    <button type="submit">go to</button>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<style>
    .body_inner {
        display: flex;
        flex-direction: column;
    }

    .categories {
        position: absolute;
        left: 50%;
        top: 25%;
        bottom: 0;
        transform: translate(-50%);
    }
    
    .category {
        display: flex;
        flex-direction: row;
    }

    .category_image_inner {
        height: 300px;
        width: 300px;
    }
</style>