    <div class="body" align="center">
        <div class="goods" >
            <?php
            /** @var \App\Entity\Good $good */
            foreach ($goods as $good):
                ?>
                <div class="good">
                    <div class="good_image">
                        <img class="good_image_inner" src="<?= $good->getImage(); ?>"
                    </div>

                    <div class="good_name">
                        <h3><?= $good->getName(); ?></h3>
                    </div>

                    <div class="good_color">
                        <span><?= $good->getColor(); ?></span>
                    </div>

                    <div class="good_size">
                        <span><?= $good->getSize(); ?></span>
                    </div>

                    <div class="good_price">
                        <h4>$<?= $good->getPrice(); ?></h4>
                    </div>

                    <form class="form" action="/add_to_cart" method="POST">
                        <div class="good_add-to-cart_button">
                            <input type="hidden" name="goodId" value="<?= $good->getId(); ?>">

<!--                            <input type="submit" value="add to cart">-->
                            <button type="submit">add to cart</button>
                        </div>
                    </form>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

<style>
    .goods {
        position: absolute;
        left: 50%;
        top: 25%;
        bottom: 0;
        transform: translate(-50%);
    }

    .good {
        display: flex;
        flex-direction: row;
    }

    .good_image_inner {
        height: 300px;
        width: 300px;
    }
</style>

<script
    src="https://code.jquery.com/jquery-3.7.0.min.js"
    integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g="
    crossorigin="anonymous">
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $('.form button').click(function (){
            var parent = $(this).parent();
            var goodId = parent.find("[name='goodId']").attr('value');
            $.post( "/add_to_cart", {goodId: goodId}, function( data ) {
                // alert(data);
                $('.cart-quantity').html(data);
            });
            return false;
        });
    });
</script>