    <div class="body" align="center">
        <div class="goods" >
            <?php
            /** @var \App\Entity\Good $good */
            foreach ($goods as $good):
                ?>
                <div class="good">
                    <div class="good_image">
                        <img class="good_image_inner" src="<?= $good->getImage(); ?>"
                    </div>

                    <div class="good_name">
                        <h3><?= $good->getName(); ?></h3>
                    </div>

                    <div class="good_color">
                        <span><?= $good->getColor(); ?></span>
                    </div>

                    <div class="good_size">
                        <span><?= $good->getSize(); ?></span>
                    </div>

                    <div class="good_price">
                        <h4>$<?= $good->getPrice(); ?></h4>
                    </div>

                    <form action="/add_to_cart" method="POST">
                        <div class="good_add-to-cart_button">
                            <input type="hidden" name="goodId" value="<?= $good->getId(); ?>">

                            <input type="submit" value="add to cart">
                        </div>
                    </form>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

<?php

if ($_SERVER['REQUEST_METHOD'] === 'POST') print_r($_POST);

//print_r($_SERVER);

?>
<style>
    .goods {
        position: absolute;
        left: 50%;
        top: 30%;
        bottom: 0;
        transform: translate(-50%);
    }

    .good {
        display: flex;
        flex-direction: row;
    }

    .good_image_inner {
        height: 300px;
        weight: 300px;
    }
</style>