<header>
    <h1 class="header_name" align="center">the market</h1>
</header>
<body>
    {content}
</body>
<footer>
    <div class="services" align="center">
        <div class="service">
            <img class="service_logo" src="https://cdn-icons-png.flaticon.com/512/87/87390.png">
        </div>

        <div class="service">
            <img class="service_logo" src="https://cdns.iconmonstr.com/wp-content/releases/preview/2018/240/iconmonstr-telegram-1.png">
        </div>

        <div class="service">
            <img class="service_logo" src="https://creazilla-store.fra1.digitaloceanspaces.com/icons/3237971/soundcloud-circle-icon-md.png">
        </div>
    </div>
</footer>

<style>
    header {
        margin-top: 10px;
        padding-top: 10px;
    }

    .header_name {
        font-family: "PT Mono", serif;
    }

    .services {
        display: flex;
        flex-direction: row;
    }

    .service {
        margin: 10px;
        padding: 10px;
    }

    .service_logo {
        height: 50px;
        width: 50px;
    }

    footer {
        position: absolute;
        left: 50%;
        bottom: 0;
        width: 100%;
        /*height: 80px;*/
        transform: translate(-15%, -10%);
    }
</style>